### ISSUE TITLE
[INFO] Creation of PKGBUILD for BlackArch Windows category

### ISSUE THREAD

**Issue by D3vil0p3r** [last-byte/PersistenceSniper#15]
Hey, I created an Arch Linux package of PersistenceSniper for [blackarch-windows](https://blackarch.org/windows.html) and [blackarch-defensive](https://blackarch.org/defensive.html) categories in order to be installed by `pacman -S persistencesniper` and then deployed to a Windows environment.

It will be available when the PR will be merged in few days.

You can find the PR here: https://github.com/BlackArch/blackarch/pull/3822

Cheers

AV

**Comment by last-byte** [comment]
Appreciate it mate, great idea!
