### ISSUE TITLE
Parse-NetUser function is not locale-agnostic

### ISSUE THREAD

**Issue by eirnym** [last-byte/PersistenceSniper#20]
Thank you for your great tool

I found that on non-English Windows localisation, I have false positives from the first and the last line (a record per word). The screenshot below shows current users and a different line on the bottom. 

I suggest to rewrite `Parse-NetUser` function filter out anything above `------`, empty lines and don't parse the last line. E.g. on next line parse previous line if any. This would harden this function and won't rely on English locale messages.

To translate some messages:
`Konta użytkowników dla` - `User accounts for`
`Gość` - `Guest`
`Domyślny użytkownik` - `Default user`
`Polecenie zostało wykonane pomyślnie.` - `The command completed`

Green boxes on a screenshot hide private information like username and computer name.

![2023-10-18_11_09_4682078-000030-Wiersz polecenia](https://github.com/last-byte/PersistenceSniper/assets/485399/c52334b5-884b-4f6e-8234-f0fe8f85a1a1)

**Comment by last-byte** [comment]
Hi, this issue has been fixed in version 1.14.0. I modified Parse-NetUser so that it discards lines which end with a dot, a thing that happens only to the "The command completed..." line.

**Comment by eirnym** [comment]
Are you sure that any username can't end with a dot?

**Comment by last-byte** [comment]
Looks like so to me
![Screenshot 2023-11-07 215442](https://github.com/last-byte/PersistenceSniper/assets/23014667/0f8413fc-40c5-4d1f-87a2-5a9147af596a)
