### ISSUE TITLE
Installation help

### ISSUE THREAD

**Issue by daniele777** [last-byte/PersistenceSniper#26]
Hy i have this error 

ackageManagement\Install-Package : Nessuna corrispondenza trovata per i criteri di ricerca specificati e il nome di
pacchetto 'PersistenceSniper'. Prova Get-PSRepository per visualizzare tutte le origini dei pacchetti registrate
disponibili.
In C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1809 car:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Ex
   ception
    + FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage

Help :)

**Comment by last-byte** [comment]
Hi, would you mind sending the command you run and a screenshot of the error?

**Comment by daniele777** [comment]
Can i install module offline? 
use this command
Install-Module PersistenceSniper

Put files under ..\Documents\WindowsPowerShell\Modules
