### ISSUE TITLE
PendingFileRenameOperations for disabling AV/EDRs

### ISSUE THREAD

**Issue by mnrkbys** [last-byte/PersistenceSniper#29]
`HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\PendingFileRenameOperations` can be used to disable AV/EDRs.
However, PersistenceSniper does not seem to detect it.

https://x.com/rad9800/status/1867511624149741828
https://github.com/rad9800/FileRenameJunctionsEDRDisable

**Comment by last-byte** [comment]
Hi! While this is an interesting method to disable an EDR on a system, it's not a persistence technique by itself, as it does not allow a malicious actor to execute arbitrary code or commands. I am going to close this issue.
