### ISSUE TITLE
Dependency

### ISSUE THREAD

**Issue by sreejith111988** [last-byte/PersistenceSniper#6]
The module in PS gallery and details here does not indicate any dependency. However, when attempting to import the module of PS version 4 indicates that PersistenceSniper requires PS version 5. Please clarify

**Comment by last-byte** [comment]
This is not a dependency issue, as “dependencies” in Powershell are other scripts/modules needed for execution, which PersistenceSniper does not need. Furthermore, on PS Gallery and in the module manifest it is clearly specified that the module requires PS version 5.0. I am going to close this issue. 
![FC9D90BD-23FF-4D93-8E34-5653BABAA468](https://user-images.githubusercontent.com/23014667/186220700-9018807d-e0c5-47e2-b4af-241192af3892.jpeg)
